kind: Service
apiVersion: v1
metadata:
# set your user name
  name: opesi-hello-world
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
# set your user name
    app: opesi-hello-world